#!/usr/bin/env ruby

# Mass - A DevOps thingy.
# ~~~~~~~~~~~~~~~~~~~~~~~

$LOAD_PATH.unshift(File.join(File.dirname(__FILE__), 'lib'))
$LOAD_PATH.unshift('/usr/local/lib/mass/lib')

require 'yaml'
require 'awesome_print'

# Project specific modules
require 'cloud'
require 'printer'
require 'parameters'
require 'configuration'

$version = '0.1'
$connections = Hash.new

class Mass
  def initialize
    # Setting up global variables for configuration and parameters.
    # Those variables are available from all other modules and libraries
    # within this program.
    $params       = Parameters.parse
    $config       = Configuration.parse

    # At this stage we can connect to cloud of our choice, or at least try to
    Cloud.connect
    # Actually doing something
    Parameters.act
  end
end

if (__FILE__ == $0)
  m = Mass.new
end